version: '3.8'

services:
  mongodb:
    image: mongo:latest-windowsservercore
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db
      - ./REPORT_SIMO/mongo-init/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - ./REPORT_SIMO/mongo-init/init_templates.json:/docker-entrypoint-initdb.d/init_templates.json:ro
      - ./REPORT_SIMO/mongo-init/init_users.json:/docker-entrypoint-initdb.d/init_users.json:ro

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: simo_backend_img
    container_name: SIMO_BACKEND_IMG
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin123@mongodb:27017/?authSource=admin
    depends_on:
      - mongodb

volumes:
  mongo-data:
